# Generated by Django 3.1.7 on 2021-03-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='text',
            field=models.CharField(default='defaultext', max_length=30),
            preserve_default=False,
        ),
    ]
