# Generated by Django 3.1.7 on 2021-03-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='submissions_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
